<?php
require_once __DIR__.'/../../config/auth.php';require_once __DIR__.'/../../config/database.php';require_once __DIR__.'/../../config/helper.php';require_admin();
$pdo=db();$id=max(0,(int)($_GET['id']??0));if(!$pdo||!$id){flash('error','Pengguna tidak ditemukan.');redirect('admin/user/index.php');}
$s=$pdo->prepare('SELECT id,nama,username,role,created_at FROM users WHERE id=?');$s->execute([$id]);$row=$s->fetch();if(!$row){flash('error','Pengguna tidak ditemukan.');redirect('admin/user/index.php');}
$summary=['total'=>0,'avg'=>0,'best'=>0];$scores=[];
if($row['role']==='siswa'){$s=$pdo->prepare('SELECT COUNT(*) total,COALESCE(ROUND(AVG(skor)),0) avg_score,COALESCE(MAX(skor),0) best FROM nilai WHERE user_id=?');$s->execute([$id]);$x=$s->fetch();$summary=['total'=>(int)$x['total'],'avg'=>(int)$x['avg_score'],'best'=>(int)$x['best']];$s=$pdo->prepare('SELECT jenis,skor,created_at FROM nilai WHERE user_id=? ORDER BY id DESC LIMIT 10');$s->execute([$id]);$scores=$s->fetchAll();}
$adminPageTitle='Detail Pengguna';$adminPageDescription='Informasi akun dan riwayat belajar.';$adminActive='user';include __DIR__.'/../../includes/admin_header.php';
?>
<div class="admin-columns"><section class="admin-card"><div class="admin-card-head"><div><h2><?=e($row['nama'])?></h2><p>@<?=e($row['username'])?></p></div><span class="role-badge <?=e($row['role'])?>"><?=e(ucfirst($row['role']))?></span></div><div class="content-card sky"><p><strong>ID akun:</strong> <?= (int)$row['id'] ?></p><p><strong>Dibuat:</strong> <?=e(format_date_id($row['created_at']))?></p></div><div class="admin-form-actions"><a class="btn" href="<?=url('admin/user/edit.php?id='.$id)?>">Edit Akun</a><a class="btn ghost" href="<?=url('admin/user/reset-password.php?id='.$id)?>">Reset Password</a><a class="btn outline" href="<?=url('admin/user/index.php')?>">Kembali</a></div></section>
<section class="admin-card"><div class="admin-card-head"><div><h2>Ringkasan Belajar</h2><p>Khusus akun siswa.</p></div></div><div class="admin-grid" style="grid-template-columns:repeat(3,1fr)"><div class="admin-stat"><strong><?=$summary['total']?></strong><span>Aktivitas</span></div><div class="admin-stat mint"><strong><?=$summary['avg']?></strong><span>Rata-rata</span></div><div class="admin-stat sun"><strong><?=$summary['best']?></strong><span>Terbaik</span></div></div></section></div>
<section class="admin-card" style="margin-top:18px"><div class="admin-card-head"><div><h2>Riwayat Nilai</h2><p>Sepuluh aktivitas terbaru.</p></div></div><?php if($scores):?><div class="admin-table-wrap"><table><thead><tr><th>Aktivitas</th><th>Skor</th><th>Waktu</th></tr></thead><tbody><?php foreach($scores as $score):?><tr><td><?=e($score['jenis'])?></td><td><strong><?=$score['skor']?></strong></td><td><?=e(format_date_id($score['created_at']))?></td></tr><?php endforeach;?></tbody></table></div><?php else:?><div class="admin-empty"><span>⭐</span><strong>Belum ada nilai</strong><small>Akun ini belum menyelesaikan aktivitas atau bukan akun siswa.</small></div><?php endif;?></section>
<?php include __DIR__.'/../../includes/admin_footer.php'; ?>
